### ISSUE TITLE
Missing readthedocs reference

### ISSUE THREAD

**Issue by rkokkelk** [inhumantsar/python-ansible-vault-rekey#355]
The readthedocs link has been deprecated and now results in a 404 on readthedocs. So the documentation previously hosted there is now missing. Might it be possible to reinstate the documentation?

**Comment by inhumantsar** [comment]
iirc the link comes from a cookiecutter i used to start this. there never was one.

we can either toss the link or start using RTD.

**Comment by rkokkelk** [comment]
Ah good to know, I think just the help is sufficient. No need to create a complete RTD. I'll just remove the link.
